/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 */

tasks.register("configured") {
    println("This is executed during the configuration phase")
}

tasks.register("test") {
    doLast {
        println("This is executed during the execution phase")
    }
}